### ISSUE TITLE
Update `set-value` dependency to `3.0.1` or later

### ISSUE THREAD

**Issue by kram0120** [jonschlinkert/cache-base#14]
Please update to `set-value` v3.0.1 to bring in the recent security patch.

**Comment by doowb** [comment]
`set-value` has version `3.0.0` in the `package.json` which means that `3.0.1` will be installed. If it's not, then please take a look at [this guide](https://gist.github.com/jonschlinkert/9a62534c4f8bc76aee6058caa3f05fd6) with more information on how to clear caches and update lock files.
