### ISSUE TITLE
[Security Vulnerability] in cache-base v1, v2 and v3 / used by Webpack

### ISSUE THREAD

**Issue by deleonio** [jonschlinkert/cache-base#20]
Hello @jonschlinkert,

there is a security vulnerability in cache-base. Is it possible to fix that?!

Link: https://snyk.io/test/npm/cache-base/1

**Comment by deleonio** [comment]
https://github.com/webpack/webpack/issues/12286

**Comment by jonschlinkert** [comment]
There is no vulnerability. The report was made in error. 

This library uses `set-value`, which already ignores unsafe keys: https://github.com/jonschlinkert/set-value/blob/master/index.js#L102.
