### ISSUE TITLE
fix documentation or make it real

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/cache-base#4]
It shows that default writing is to `app.cache` but it writes to `app`.
So, PR for fix or PR for `module.exports = namespace('cache')`?

**Comment by jonschlinkert** [comment]
let's just fix the docs, this is stable and heavily used

**Comment by jonschlinkert** [comment]
thanks for finding it

**Comment by tunnckoCore** [comment]
Yea, know. Okey.

**Comment by jonschlinkert** [comment]
closing since the API was changed and this is no longer necessary
