### ISSUE TITLE
remove support for setting on the root of the cache

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/cache-base#8]
I've never been a fan of settings values on the root, as it creates potential for conflicts, makes it harder to get the actually user-defined values, et cetera. 

I think we should just set values on `.cache` by default, or a property specified by the user. 

The consequence of this change is that you won't be able to directly get or set values from the root of the instance of `cacheBase`, you'd have to get and set on `cacheBase.cache` or whatever property was defined. 

@doowb any thoughts? can you think of other side effects of removing support for getting/setting on the root of the object? will it materially change how we do things in other libs?

**Comment by doowb** [comment]
I think using a `.cache` property is a good idea. I think we had originally done this as a convenience for setting properties and methods on objects, but we don't do that with these methods anymore. If we have places that are using these to set properties like that then we can update them and it will be more explicit about what we intend.

**Comment by jonschlinkert** [comment]
closed by 3.0
